### ISSUE TITLE
Level ends before all enemies eliminated

### ISSUE THREAD

**Issue by xelaadryth** [madl3r/Ellipsis2.0#10]
Make sure that the system that detects enemies added and removed from a level is accurate at detecting end of level. Right now the shooty lane enemy may persist between levels.

**Comment by madl3r** [comment]
Fixed!! Turns out that enemies that were moving horizontally occasionally trigger damage more than once from the same bullet. When enemies died at the same time as a double hit detect it would count that enemy as being killed twice in terms of the count of how many enemies have been killed in a round. Base enemy was given a variable for tracking if it should be alive. When hp goes to 0 or below this variable is switched to dead so that it only sends it's death message a single time.
